# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    # (this is just an example, not intended to be a production configuration)

  adminer:
    imager: adminer
    restart: always
    ports:
      - 8080:8080
